// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// Validate environment variables
if (!SUPABASE_URL || SUPABASE_URL === 'your_supabase_url_here' || SUPABASE_URL === '') {
  console.error('❌ NEXT_PUBLIC_SUPABASE_URL is not configured. Please create a .env.local file with your Supabase credentials.');
  console.error('📝 Example: NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co');
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === 'your_anon_key_here' || SUPABASE_PUBLISHABLE_KEY === '') {
  console.error('❌ NEXT_PUBLIC_SUPABASE_ANON_KEY is not configured. Please create a .env.local file with your Supabase credentials.');
  console.error('📝 Example: NEXT_PUBLIC_SUPABASE_ANON_KEY=your_actual_anon_key_here');
}

// Create client with fallback for development
const supabaseUrl = SUPABASE_URL || 'https://vpysqshhafthuxvokwqj.supabase.co';
const supabaseKey = SUPABASE_PUBLISHABLE_KEY || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'publishare-web'
    }
  }
});
